name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  python-docker-cpu:
    runs-on: [self-hosted, python-docker]
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push python:base
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./base
          file: ./base/Dockerfile
          tags: |
            ghcr.io/kbc8894/python:${{ matrix.python-version }}-base-cpu
            ghcr.io/kbc8894/python:${{ matrix.python-version }}-base
            ghcr.io/kbc8894/python:${{ matrix.python-version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
      - name: Build and push python:minimal
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./minimal
          file: ./minimal/Dockerfile
          tags: |
            ghcr.io/kbc8894/python:${{ matrix.python-version }}-minimal-cpu
            ghcr.io/kbc8894/python:${{ matrix.python-version }}-minimal
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            BASE_CONTAINER=ghcr.io/kbc8894/python:${{ matrix.python-version }}-base
      - name: Build and push python:pytorch
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./pytorch
          file: ./pytorch/Dockerfile
          tags: |
            ghcr.io/kbc8894/python:${{ matrix.python-version }}-pytorch-cpu
            ghcr.io/kbc8894/python:${{ matrix.python-version }}-pytorch
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            BASE_CONTAINER=ghcr.io/kbc8894/python:${{ matrix.python-version }}-minimal



  python-docker-gpu:
    runs-on: [self-hosted, python-docker]
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push python:base-gpu
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./base
          file: ./base/Dockerfile
          tags: ghcr.io/kbc8894/python:${{ matrix.python-version }}-base-gpu
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            BASE_CONTAINER=nvidia/cuda:11.1-cudnn8-runtime-ubuntu18.04
      - name: Build and push python:minimal-gpu
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./minimal
          file: ./minimal/Dockerfile
          tags: ghcr.io/kbc8894/python:${{ matrix.python-version }}-minimal-gpu
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            BASE_CONTAINER=ghcr.io/kbc8894/python:${{ matrix.python-version }}-base-gpu
      - name: Build and push python:pytorch-gpu
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./pytorch
          file: ./pytorch/Dockerfile.gpu
          tags: ghcr.io/kbc8894/python:${{ matrix.python-version }}-pytorch-gpu
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            BASE_CONTAINER=ghcr.io/kbc8894/python:${{ matrix.python-version }}-minimal-gpu